stages:
    - build
    - deploy

frontend_build:
    stage: build
    tags:
        - capstone
        - linux
    script:
        - node --version
        - npm --version
        - npm ci
        - npm run build
    artifacts:
        paths: 
            - ./build
        
frontend-deploy:
  stage: deploy
  tags:
    - capstone
    - linux
  before_script:
        - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan 10.139.166.48 >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
  script:
      - mv --recursive ./build /var/www/
    
